name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: verify
    attributes:
      label: Check Existing Issues
      description: |
        Before submitting this issue, please confirm the following:
      options:
        - label: Yes, I have checked existing issues to ensure this problem hasn't already been reported.
          required: true
  - type: dropdown
    id: instrument
    attributes:
      label: Instrument or Category
      description: Which instrument or piece of code were you running?
      multiple: true
      options:
        - NIRCam Stage 1/2 Pipeline
        - MIRI Stage 1/2 Pipeline
        - Image Tools
        - PSF Subtraction
        - Analysis Tools
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe what happened and/or what you expected to happen.
      placeholder: Describe the issue and/or expected outcome.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error traceback output
      description: Please copy and paste the full traceback of the error you encountered.
      placeholder: Paste the error traceback here.
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: What operating system are you using?
      placeholder: E.g., Windows 11; Mac OS 10.10 El Capitan
  - type: input
    id: python_version
    attributes:
      label: What version of Python are you running?
      description: If you're not sure, open a terminal with the environment you're running spaceKLIP in and type "python --version"
      placeholder: E.g., Python 3.7
  - type: textarea
    id: package_list
    attributes:
      label: What Python packages do you have installed?
      description: To get a full list, open a terminal with the environment you're running spaceKLIP in and type "conda list". Paste the full output here.
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! After you submit this issue, check this GitHub thread for any updates/responses from the spaceKLIP team.
