name: Documentation Issue or Request
description: Report issues or suggest improvements to the spaceKLIP documentation.
title: "[Documentation]: "
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our documentation! Please fill out the sections below and after you submit this issue, check this GitHub thread for any updates/responses from the spaceKLIP team.
  - type: textarea
    id: problem-description
    attributes:
      label: Describe the issue or suggest an improvement
      description: |
        Please describe any issues with our documentation or suggest improvements. Your feedback is appreciated!
      placeholder: Describe the issue or suggest improvments here.
    validations:
      required: true
  - type: textarea
    id: page-urls
    attributes:
      label: URLs of the documentation pages (if applicable)
      description: |
        If the issue is specific to particular pages, provide the URLs here.
        This helps us locate and address the issue more efficiently. You can list multiple URLs if needed.
      placeholder: Enter the URLs.
  - type: checkboxes
    id: verify
    attributes:
      label: Verification
      description: |
        Before submitting this issue, please verify the following:
        - You have checked existing issues to ensure this problem hasn't already been reported.
      options:
        - label: Yes, I have checked existing issues.
          required: true
