name: Documentation Issue or Request
description: Report issues or suggest improvements to the spaceKLIP documentation.
title: "[Documentation]: "
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our documentation! Please fill out the sections below and after you submit this issue, check this GitHub thread for any updates/responses from the spaceKLIP team.
  - type: textarea
    id: problem-description
    attributes:
      label: Describe the issue or suggest an improvement
      description: |
        Please describe any issues with our documentation or suggest improvements. Your feedback is appreciated!
      placeholder: Describe the issue or suggest improvments here.
    validations:
      required: true
  - type: input
    id: page-url
    attributes:
      label: URL of the documentation page (if applicable).
      description: |
        If the issue is specific to a particular page, provide the URL here.
        This helps us locate and address the issue more efficiently.
      placeholder: Enter the URL.

